[package]
name = "quickjs-oxide-test262"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
quickjs-oxide-host = { workspace = true }

[dependencies.quickjs-oxide]
workspace = true
features = ["test262-host"]
[[bin]]
name = "run-test262"
path = "src/main.rs"
