use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

struct Fixture {
    root: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let id = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "quickjs-oxide-rust-only-{}-{id}",
            std::process::id()
        ));
        if root.exists() {
            fs::remove_dir_all(&root).expect("remove stale rust-only fixture");
        }

        fs::create_dir_all(root.join("src")).expect("create fixture src directory");
        write(
            &root.join("Cargo.toml"),
            r#"[package]
name = "rust-only-fixture"
version = "0.1.0"
edition = "2024"

[workspace]
"#,
        );
        write(&root.join("src/lib.rs"), "pub fn answer() -> u8 { 42 }\n");
        write(
            &root.join("Cargo.lock"),
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "rust-only-fixture"
version = "0.1.0"
"#,
        );

        Self { root }
    }

    fn write(&self, relative: &str, contents: &str) {
        write(&self.root.join(relative), contents);
    }

    fn run_gate(&self) -> Output {
        Command::new("bash")
            .arg(gate_script())
            .env("RUST_ONLY_ROOT", &self.root)
            .output()
            .expect("run rust-only gate")
    }

    fn refresh_lockfile(&self) {
        let output = Command::new("cargo")
            .arg("generate-lockfile")
            .arg("--offline")
            .current_dir(&self.root)
            .output()
            .expect("generate fixture Cargo.lock");
        assert_success("generate fixture Cargo.lock", &output);
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

#[test]
fn current_repository_passes_rust_only_gate() {
    let output = Command::new("bash")
        .arg(gate_script())
        .output()
        .expect("run rust-only gate against repository");
    assert_success("repository rust-only gate", &output);
}

#[test]
fn gate_allows_rust_c_abi_exports_and_test_only_qjs_oracles() {
    let fixture = Fixture::new();
    fixture.write(
        "src/lib.rs",
        r#"#[unsafe(no_mangle)]
pub extern "C" fn rust_owned_js_runtime() -> u32 { 42 }
"#,
    );
    fixture.write(
        "tests/oracle.rs",
        r#"#[test]
fn external_qjs_is_only_an_oracle() {
    let _ = std::process::Command::new("qjs").arg("--version");
}
"#,
    );
    fixture.write(
        "tests/fixtures/quickjs.c",
        "/* A native fixture is test-only and is not a product engine. */\n",
    );

    let output = fixture.run_gate();
    assert_success("allowed C ABI export and test oracle", &output);
}

#[test]
fn gate_rejects_native_sources_build_tools_links_ffi_and_runtime_delegation() {
    assert_rejected(
        |fixture| fixture.write("src/quickjs.c", "int JS_Eval(void) { return 0; }\n"),
        "native source or binary in a product path",
    );

    assert_rejected(
        |fixture| {
            fixture.write(
                "build.rs",
                "fn main() { let _builder = cc::Build::new(); }\n",
            );
        },
        "native compiler/generator configured by Cargo",
    );

    assert_rejected(
        |fixture| {
            fixture.write(
                "build.rs",
                r#"fn main() {
    println!("cargo:rustc-link-lib=static=quickjs");
}
"#,
            );
        },
        "external QuickJS native link or embed instruction",
    );

    assert_rejected(
        |fixture| {
            fixture.write(
                "src/lib.rs",
                r#"unsafe extern "C" {
    fn JS_NewRuntime() -> *mut core::ffi::c_void;
}
"#,
            );
        },
        "foreign QuickJS C API import",
    );

    assert_rejected(
        |fixture| {
            fixture.write(
                "src/lib.rs",
                r#"pub fn evaluate_elsewhere() {
    let _ = std::process::Command::new("qjs").arg("-e").arg("1 + 1");
}
"#,
            );
        },
        "external qjs execution in product code",
    );
}

#[test]
fn gate_rejects_quickjs_wrappers_after_cargo_dependency_renaming() {
    let fixture = Fixture::new();
    fixture.write(
        "Cargo.toml",
        r#"[package]
name = "rust-only-fixture"
version = "0.1.0"
edition = "2024"

[dependencies]
innocent_alias = { package = "rquickjs-sys", path = "vendor/bridge" }

[workspace]
"#,
    );
    fixture.write(
        "vendor/bridge/Cargo.toml",
        r#"[package]
name = "rquickjs-sys"
version = "0.1.0"
edition = "2024"
"#,
    );
    fixture.write("vendor/bridge/src/lib.rs", "pub fn hidden_wrapper() {}\n");
    fixture.refresh_lockfile();

    let output = fixture.run_gate();
    assert_failure_contains(
        "renamed QuickJS wrapper dependency",
        &output,
        "QuickJS wrapper in the resolved Cargo dependency graph",
    );
}

fn assert_rejected(configure: impl FnOnce(&Fixture), expected: &str) {
    let fixture = Fixture::new();
    configure(&fixture);
    let output = fixture.run_gate();
    assert_failure_contains(expected, &output, expected);
}

fn gate_script() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("scripts")
        .join("check-rust-only.sh")
}

fn write(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create fixture parent directory");
    }
    fs::write(path, contents).expect("write rust-only fixture file");
}

fn assert_success(context: &str, output: &Output) {
    assert!(
        output.status.success(),
        "{context} failed with {}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_failure_contains(context: &str, output: &Output, expected: &str) {
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(
        output.status.code(),
        Some(1),
        "{context} should be a policy violation\nstdout:\n{}\nstderr:\n{stderr}",
        String::from_utf8_lossy(&output.stdout)
    );
    assert!(
        stderr.contains(expected),
        "{context} did not report {expected:?}\nstdout:\n{}\nstderr:\n{stderr}",
        String::from_utf8_lossy(&output.stdout)
    );
}
