
BEGIN {
    print "// @generated by scripts/unicode/generate-unicode-case-tables.sh."
    print "// Source: QuickJS 2026-06-04 libunicode-table.h, Unicode 17.0.0."
    print "// Source SHA-256: cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c."
    print "// Derived from QuickJS MIT source and Unicode UCD data; see NOTICE and LICENSES/."
    print ""
    print "#[cfg(test)]"
    print "pub(super) const SOURCE_SHA256: &str ="
    print "    \"cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c\";"
    print ""
}
/^static const uint32_t case_conv_table1\[378\] = \{/ {
    print "pub(super) const CASE_CONV_TABLE1: [u32; 378] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t case_conv_table2\[378\] = \{/ {
    print "pub(super) const CASE_CONV_TABLE2: [u8; 378] = ["
    copying = 1
    found++
    next
}
/^static const uint16_t case_conv_ext\[58\] = \{/ {
    print "pub(super) const CASE_CONV_EXT: [u16; 58] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_Cased1_table\[190\] = \{/ {
    print "pub(super) const CASED_TABLE: [u8; 190] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_Cased1_index\[18\] = \{/ {
    print "pub(super) const CASED_INDEX: [u8; 18] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_Case_Ignorable_table\[785\] = \{/ {
    print "pub(super) const CASE_IGNORABLE_TABLE: [u8; 785] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_Case_Ignorable_index\[75\] = \{/ {
    print "pub(super) const CASE_IGNORABLE_INDEX: [u8; 75] = ["
    copying = 1
    found++
    next
}
copying && /^};/ {
    print "];"
    if (found < 7)
        print ""
    copying = 0
    next
}
copying { print }
END {
    if (found != 7 || copying) {
        print "error: expected seven complete case-conversion tables" > "/dev/stderr"
        exit 1
    }
}
