
BEGIN {
    print "// @generated by scripts/unicode/generate-unicode-ident-tables.sh."
    print "// Source: QuickJS 2026-06-04 libunicode-table.h, Unicode 17.0.0."
    print "// Source SHA-256: cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c."
    print "// Derived from QuickJS MIT source and Unicode UCD data; see NOTICE and LICENSES/."
    print ""
}
/^static const uint8_t unicode_prop_ID_Start_table\[1146\] = \{/ {
    print "pub(super) const ID_START_TABLE: [u8; 1146] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Start_index\[108\] = \{/ {
    print "pub(super) const ID_START_INDEX: [u8; 108] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Continue1_table\[708\] = \{/ {
    print "pub(super) const ID_CONTINUE_TABLE: [u8; 708] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Continue1_index\[66\] = \{/ {
    print "pub(super) const ID_CONTINUE_INDEX: [u8; 66] = ["
    copying = 1
    found++
    next
}
copying && /^};/ {
    print "];"
    if (found < 4)
        print ""
    copying = 0
    next
}
copying { print }
END {
    if (found != 4 || copying) {
        print "error: expected four complete identifier tables" > "/dev/stderr"
        exit 1
    }
}
