#!/usr/bin/env bash
# Regenerate the Rust-only Unicode identifier tables from the checksum-pinned
# QuickJS 2026-06-04 oracle source. Product builds consume only the generated
# Rust arrays and never read, compile, or link the upstream C source.

set -euo pipefail

if (( $# < 1 || $# > 2 )); then
    echo "usage: $0 /path/to/quickjs-2026-06-04/libunicode-table.h [output.rs]" >&2
    exit 2
fi

source_file=$1
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output_file=${2:-"$script_dir/../src/unicode_ident_tables.rs"}
expected_sha256=cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c
if command -v sha256sum >/dev/null 2>&1; then
    actual_sha256=$(sha256sum "$source_file" | awk '{ print $1 }')
elif command -v shasum >/dev/null 2>&1; then
    actual_sha256=$(shasum -a 256 "$source_file" | awk '{ print $1 }')
else
    echo "error: sha256sum or shasum is required to verify the Unicode source" >&2
    exit 2
fi
if [[ "$actual_sha256" != "$expected_sha256" ]]; then
    echo "error: unexpected libunicode-table.h checksum: $actual_sha256" >&2
    exit 1
fi

tmp_file=$(mktemp "${TMPDIR:-/tmp}/quickjs-oxide-unicode-ident.XXXXXX")
trap 'rm -f -- "$tmp_file"' EXIT HUP INT TERM

awk '
BEGIN {
    print "// @generated by scripts/generate-unicode-ident-tables.sh."
    print "// Source: QuickJS 2026-06-04 libunicode-table.h, Unicode 17.0.0."
    print "// Source SHA-256: cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c."
    print "// Derived from QuickJS MIT source and Unicode UCD data; see NOTICE and LICENSES/."
    print ""
}
/^static const uint8_t unicode_prop_ID_Start_table\[1146\] = \{/ {
    print "pub(super) const ID_START_TABLE: [u8; 1146] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Start_index\[108\] = \{/ {
    print "pub(super) const ID_START_INDEX: [u8; 108] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Continue1_table\[708\] = \{/ {
    print "pub(super) const ID_CONTINUE_TABLE: [u8; 708] = ["
    copying = 1
    found++
    next
}
/^static const uint8_t unicode_prop_ID_Continue1_index\[66\] = \{/ {
    print "pub(super) const ID_CONTINUE_INDEX: [u8; 66] = ["
    copying = 1
    found++
    next
}
copying && /^};/ {
    print "];"
    if (found < 4)
        print ""
    copying = 0
    next
}
copying { print }
END {
    if (found != 4 || copying) {
        print "error: expected four complete identifier tables" > "/dev/stderr"
        exit 1
    }
}
' "$source_file" >"$tmp_file"

mkdir -p -- "$(dirname -- "$output_file")"
chmod 0644 "$tmp_file"
mv -- "$tmp_file" "$output_file"
trap - EXIT HUP INT TERM
