#!/usr/bin/env python3
"""Generate Rust Unicode-normalization tables from pinned QuickJS source."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys


EXPECTED_SHA256 = "cf782bc7a07549e976f606bd3cb8555858482b279574554dcb8d46412986006c"
TABLES = (
    ("unicode_cc_table", "UNICODE_CC_TABLE", "u8", 937),
    ("unicode_cc_index", "UNICODE_CC_INDEX", "u8", 90),
    ("unicode_decomp_table1", "UNICODE_DECOMP_TABLE1", "u32", 709),
    ("unicode_decomp_table2", "UNICODE_DECOMP_TABLE2", "u16", 709),
    ("unicode_decomp_data", "UNICODE_DECOMP_DATA", "u8", 9_452),
    ("unicode_comp_table", "UNICODE_COMP_TABLE", "u16", 965),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "extract the normalization tables from QuickJS 2026-06-04 "
            "libunicode-table.h"
        )
    )
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument(
        "output",
        nargs="?",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent
        / "src"
        / "unicode_normalize_tables.rs",
    )
    return parser.parse_args()


def extract_table(source: str, c_name: str, rust_type: str, count: int) -> list[int]:
    pattern = re.compile(
        rf"static\s+const\s+{re.escape(rust_type.replace('u', 'uint'))}_t\s+"
        rf"{re.escape(c_name)}\[{count}\]\s*=\s*\{{(?P<body>.*?)\}};",
        re.DOTALL,
    )
    match = pattern.search(source)
    if match is None:
        raise ValueError(f"missing {c_name}[{count}]")
    body = re.sub(r"/\*.*?\*/", "", match.group("body"), flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    values = [int(token, 0) for token in re.findall(r"0[xX][0-9a-fA-F]+|\d+", body)]
    if len(values) != count:
        raise ValueError(f"{c_name}: expected {count} values, found {len(values)}")
    width = int(rust_type[1:])
    if any(value >= 1 << width for value in values):
        raise ValueError(f"{c_name}: value does not fit {rust_type}")
    return values


def format_table(rust_name: str, rust_type: str, values: list[int]) -> str:
    digits = {"u8": 2, "u16": 4, "u32": 8}[rust_type]
    per_line = {"u8": 16, "u16": 12, "u32": 8}[rust_type]
    lines = [f"pub(super) const {rust_name}: [{rust_type}; {len(values)}] = ["]
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        formatted = ", ".join(f"0x{value:0{digits}x}" for value in chunk)
        lines.append(f"    {formatted},")
    lines.append("];")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    source_bytes = args.source.read_bytes()
    actual_sha256 = hashlib.sha256(source_bytes).hexdigest()
    if actual_sha256 != EXPECTED_SHA256:
        print(
            "error: unexpected libunicode-table.h checksum: "
            f"{actual_sha256} (expected {EXPECTED_SHA256})",
            file=sys.stderr,
        )
        return 1

    source = source_bytes.decode("utf-8")
    try:
        tables = [
            (rust_name, rust_type, extract_table(source, c_name, rust_type, count))
            for c_name, rust_name, rust_type, count in TABLES
        ]
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    sections = [
        "\n".join(
            (
                "// @generated by scripts/generate-unicode-normalize-tables.py.",
                "// Source: QuickJS 2026-06-04 libunicode-table.h, Unicode 17.0.0.",
                f"// Source SHA-256: {EXPECTED_SHA256}.",
                "// Derived from QuickJS MIT source and Unicode UCD data; see NOTICE and LICENSES/.",
                "",
                "#[cfg(test)]",
                "pub(super) const SOURCE_SHA256: &str =",
                f'    "{EXPECTED_SHA256}";',
            )
        )
    ]
    sections.extend(format_table(*table) for table in tables)
    output = "\n\n".join(sections) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
