"""Pinned data and expected shapes for exception_evidence."""

STAGE3D_TEST_CONTRACTS = (('src/engine/code/binary_object/function_translate/capability.rs',
  'ordinary_throw_rows_are_the_exact_reviewed_completion_set',
  ('CAPABILITY_REGISTRY[48].policy',
   'CapabilityPolicy::OrdinaryOnly(Recipe::Throw)',
   'CAPABILITY_REGISTRY[47].policy',
   'CapabilityPolicy::OrdinaryOnly(Recipe::ThrowReadOnly)')),
 ('src/engine/code/binary_object/function_translate/mod.rs',
  'explicit_throw_lowering_is_typed_and_operand_free',
  ('lower_operation(Recipe::Throw, &NativeOperands::None).unwrap()',
   'Some(PendingOperation::Ready(FunctionOp::Throw))',
   'assert!(operations.next().is_none());')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'lowers_representative_sanitized_operations_without_consulting_diagnostics',
  ('(FunctionOp::Throw, OrdinaryLeafOp::Throw)',)),
 ('src/engine/code/binary_object_publish.rs',
  'ordinary_leaf_draft_ops_lower_one_for_one_without_reordering',
  ('lower(OrdinaryLeafOp::Throw)', 'Instruction::Throw')),
 ('src/engine/code/bytecode.rs',
  'verifier_allows_terminal_completion_to_abandon_switch_values',
  ('for completion in [Instruction::Return, Instruction::Throw]',
   'assert_eq!(function.verify().unwrap().max_stack, 2);')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_throw_uses_the_exact_wire_metadata_and_value_identity',
  ('assert_eq!(QUICKJS_ORDINARY_THROW_BC5.len(), 45);',
   '0x73cf_217e_06c5_fee2',
   '[Instruction::GetArg(0), Instruction::Throw]',
   'snapshot.metadata.function_kind, FunctionKind::Normal',
   'Some(Value::Object(object.clone()))',
   'Some(Value::Int(42))')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_throw_reenters_caller_catch_backtrace_and_iterator_close',
  ('eval_with_filename(',
   'Value::Bool(true)',
   'let stack = own_stack_string(&runtime, &error).to_utf8_lossy();',
   'JsString::from_static(',
   'assert!(!context.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_throw_is_terminal_and_branch_targetable',
  ('quickjs_ordinary_one_argument_with_code(&[0xcf, 0x30, 0x0e], 1)',
   'Instruction::Throw, Instruction::Drop',
   'quickjs_ordinary_one_argument_with_code(&[0xcf, 0xea, 0x02, 0xb4, 0x30], 1)',
   'Instruction::Goto(3)',
   'Some(Value::Object(object))')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_throw_verification_rejects_transactionally_and_retries',
  ('quickjs_ordinary_one_argument_with_code(code, max_stack)',
   'assert_eq!(runtime.heap_counts(), baseline',
   'assert_eq!(runtime.test_atom_count(), baseline_atoms',
   'read_trusted_ordinary_function(QUICKJS_ORDINARY_THROW_BC5, 0)',
   'Some(Value::Int(42))')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_throw_rejects_nonordinary_metadata_transactionally',
  ('async_function[28] |= 1 << 2;',
   'generator[26] |= 1 << 4;',
   'derived[26] |= 1 << 2;',
   '&image[43..], [0xcf, 0x30]',
   '.read_trusted_ordinary_function(&image, 0)',
   'assert_eq!(runtime.heap_counts(), baseline',
   'read_trusted_ordinary_function(QUICKJS_ORDINARY_THROW_BC5, 0)',
   'Some(Value::Int(42))')))

STAGE3D_TEST_BODY_HASHES = {('src/engine/code/binary_object/function_translate/capability.rs', 'ordinary_throw_rows_are_the_exact_reviewed_completion_set'): '46280b952611f2513c2764859dacaa8b0b2be02d86a0ffbf92a0d5791e7deb6a',
 ('src/engine/code/binary_object/function_translate/mod.rs', 'explicit_throw_lowering_is_typed_and_operand_free'): '5d6d1b5266a7b7682c26a39d8b54c4b9f450670feb7dc917e89427293f92b9a9',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'lowers_representative_sanitized_operations_without_consulting_diagnostics'): 'fc152214094cc8dfa8f6e068f8f67a7a05ec3b88aa50dda9290a5970af0ad92a',
 ('src/engine/code/binary_object_publish.rs', 'ordinary_leaf_draft_ops_lower_one_for_one_without_reordering'): '5d1aba35fd5745d682ef784539053160d709ebc61224ae304559d8ce1097f772',
 ('src/engine/code/bytecode.rs', 'verifier_allows_terminal_completion_to_abandon_switch_values'): 'afb4d1edcc8b4bd6f31e68faab721ffe05ad8d894a0661ad1e2d1455d282be69',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_throw_uses_the_exact_wire_metadata_and_value_identity'): 'f3df4f2957a2d447ff0f0c1af7c0cb74eb03017dda72210b1349f16d4dceccfb',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_throw_reenters_caller_catch_backtrace_and_iterator_close'): 'c696d730ba43f692e5ce7e581377f6586b88b7cc25e26b21abc2f2dd84e55fc2',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_throw_is_terminal_and_branch_targetable'): '54f139dbfa37ab0fc7b8e6f2ae09a9246d61fd2ebffdb055d86c3ccdcd1067ef',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_throw_verification_rejects_transactionally_and_retries'): 'a84862beab3d71440a66f2fd35e7dfaabe35d668b1ae51831376636b7d1cd156',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_throw_rejects_nonordinary_metadata_transactionally'): '5c92b46b6a9c05b16802f6ff26de4fef8e5ad509e6e15763f46d62e2f9dc8d27'}

STAGE3E_TEST_CONTRACTS = (('src/engine/code/binary_object/function_translate/capability.rs',
  'ordinary_throw_rows_are_the_exact_reviewed_completion_set',
  ('CAPABILITY_REGISTRY[48].policy',
   'CapabilityPolicy::OrdinaryOnly(Recipe::Throw)',
   'CAPABILITY_REGISTRY[49].policy',
   'CapabilityPolicy::OrdinaryOnly(Recipe::ThrowReadOnly)')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'lowers_property_free_read_only_with_owned_input_atom_spelling',
  ('assert_eq!(object.len(), 47);',
   'assert_eq!(draft.metadata().max_stack(), 0);',
   '[OrdinaryLeafOp::ThrowReadOnly(name)]',
   'name.0.as_ref()')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'read_only_rejects_other_subtypes_non_string_atoms_and_atom_table_drift',
  ('for subtype in [1, 2, 3, 4, 5, u8::MAX]',
   'object[46] = subtype;',
   'object[42..46].copy_from_slice(&raw_atom.to_le_bytes());',
   'unused[39] = 1;',
   'multiple[1] = 2;')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'read_only_accepts_only_string_names_under_zero_or_one_slot_provenance',
  ('predefined[1] = 0;',
   'predefined[40..44].copy_from_slice(&50_u32.to_le_bytes());',
   'manifest_alias.splice(2..4',
   'decimal_alias.splice(2..4')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'natural_read_only_wire_remains_outside_the_nonlexical_leaf_cohort',
  ('assert_eq!(object.len(), 58);', 'Err(OrdinaryLeafReadError::Unadmitted(_))')),
 ('src/engine/code/bytecode.rs',
  'verifier_rejects_bad_constants_and_stack_joins',
  ('Instruction::PostInc, Instruction::ThrowReadOnly(0)',
   'let empty_stack_readonly = DetachedBytecode::<Value>',
   'code: vec![Instruction::ThrowReadOnly(0)]',
   'assert_eq!(empty_stack_readonly.verify().unwrap().max_stack, 0);')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_read_only_uses_exact_zero_stack_wire_and_type_error',
  ('assert_eq!(QUICKJS_ORDINARY_READ_ONLY_BC5.len(), 47);',
   '0xb4c1_126c_2830_93af',
   '[Instruction::ThrowReadOnly(0)]',
   'snapshot.metadata.max_stack, 0',
   '[BytecodeConstant::Value(RawValue::String(name))]',
   'Err(RuntimeError::Exception)')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_read_only_reenters_catch_and_resets_pending_state',
  ('read_trusted_ordinary_function(QUICKJS_ORDINARY_READ_ONLY_BC5, 0)',
   'context .define_own_property(',
   'assert!(!context.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_read_only_uses_bytecode_realm_and_attaches_backtrace',
  ('let mut defining = runtime.new_context();',
   'let mut caller = runtime.new_context();',
   'runtime.get_prototype_of(&error).unwrap()',
   'own_stack_string(&runtime, &error)',
   'assert!(!caller.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_read_only_preserves_wide_lone_surrogate_name_units',
  ('image.splice(2..4, [0x05, 0x41, 0x00, 0x00, 0xd8]);',
   '.utf16_units() .collect::<Vec<_>>()',
   '0xd800',
   'assert!(!context.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_read_only_rejections_are_transactional_and_retryable',
  ('subtype_one[46] = 1;',
   'subtype_max[46] = u8::MAX;',
   'unused_atom[39] = 1;',
   'multiple_atoms[1] = 2;',
   'non_string[42..46].copy_from_slice(&0x8000_002a_u32.to_le_bytes());',
   'QUICKJS_NATURAL_READ_ONLY_BC5.to_vec()',
   'assert_eq!(runtime.heap_counts(), baseline',
   'assert_eq!(runtime.test_atom_count(), baseline_atoms')))

STAGE3E_TEST_BODY_HASHES = {('src/engine/code/binary_object/function_translate/capability.rs', 'ordinary_throw_rows_are_the_exact_reviewed_completion_set'): '46280b952611f2513c2764859dacaa8b0b2be02d86a0ffbf92a0d5791e7deb6a',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'lowers_property_free_read_only_with_owned_input_atom_spelling'): 'bc88a01461e1c7a8fc3d05e716510a81eb95b464dc48165b863b86928f970172',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'read_only_rejects_other_subtypes_non_string_atoms_and_atom_table_drift'): 'e03485e5228e1e346c83d40e2285f09283f71c94f53542af394c04a1e6b4b7aa',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'read_only_accepts_only_string_names_under_zero_or_one_slot_provenance'): '9a4fb8296751a4218e8d4c7ac672efd95c650e51c4078207af4ba625771dd609',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'natural_read_only_wire_remains_outside_the_nonlexical_leaf_cohort'): 'b50006a970fd18ce24274af96ee39394e04ae06bf27fa988682dcc3b1480741d',
 ('src/engine/code/bytecode.rs', 'verifier_rejects_bad_constants_and_stack_joins'): '745ae3d8046be141f9e42b37fe5dc36d82c602c2429f1f7b4b2c97beac918376',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_read_only_uses_exact_zero_stack_wire_and_type_error'): '29f9c54b5ccffea7e9bf100206ccaf0a99b2f4afe8d2ff887ad99b5b11989493',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_read_only_reenters_catch_and_resets_pending_state'): '756aa7b8180452d3786a16f1c2534135381e1bd4931458060ff3a5b2b6f39098',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_read_only_uses_bytecode_realm_and_attaches_backtrace'): 'fd9907b3f5987005582a5376b4305bf68cd74513bd1e46ffd59bd2933495d4d6',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_read_only_preserves_wide_lone_surrogate_name_units'): '8e220ef941cc43fa3d487827a94b1298047fd7cea6082df622788d4081b47110',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_read_only_rejections_are_transactional_and_retryable'): 'a896b877f9b5b0d49ed423701344c738937e055112695c1b264aea9ec729995a'}

STAGE3F_TEST_CONTRACTS = (('src/engine/code/binary_object/function_translate/capability.rs',
  'ordinary_nop_is_the_exact_operand_free_raw177_row',
  ('CAPABILITY_REGISTRY[177]',
   'OpcodeFormat::None',
   'CapabilityPolicy::OrdinaryOnly(Recipe::Nop)')),
 ('src/engine/code/binary_object/function_translate/mod.rs',
  'operand_free_nop_translation_is_one_typed_operation',
  ('lower_operation(Recipe::Nop, &NativeOperands::None).unwrap()',
   'Some(PendingOperation::Ready(FunctionOp::Nop))',
   'TranslationTarget::Scalar',
   'Some(PendingOperation::Ready(FunctionOp::OutsideTarget))')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'lowers_representative_sanitized_operations_without_consulting_diagnostics',
  ('(FunctionOp::Nop, OrdinaryLeafOp::Nop)',)),
 ('src/engine/code/binary_object_publish.rs',
  'ordinary_leaf_draft_ops_lower_one_for_one_without_reordering',
  ('lower(OrdinaryLeafOp::Nop)', 'Instruction::Nop')),
 ('src/engine/code/bytecode.rs',
  'verifier_accepts_closed_non_terminating_control_flow',
  ('code: vec![Instruction::Nop]', 'reachable_fallthrough.verify().unwrap_err().message()')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_nop_preserves_exact_metadata_realm_and_zero_effect',
  ('assert_eq!(QUICKJS_ORDINARY_NOP_BC5.len(), 41);',
   '0x1c52_2736_e3cb_ef92',
   '[Instruction::Nop, Instruction::ReturnUndefined]',
   'snapshot.constants.is_empty()',
   'snapshot.metadata.max_stack, 0',
   'Some(defining.function_prototype().unwrap())',
   'for _ in 0..2',
   'assert!(!caller.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_nop_only_fallthrough_rolls_back_and_retries',
  ('nop_only[37] = 1;',
   'nop_only.truncate(40);',
   'nop_only[39], 0xb1',
   'error.message(), FALLTHROUGH',
   'assert_eq!(runtime.heap_counts(), baseline',
   'assert_eq!(runtime.test_atom_count(), baseline_atoms',
   'read_trusted_ordinary_function(QUICKJS_ORDINARY_NOP_BC5, 0)',
   'assert!(!context.has_exception());')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_branch_targets_raw177_typed_index',
  ('image.extend_from_slice(&[0xea, 0x01, 0xb1, 0x29]);',
   'Instruction::Goto(1)',
   'Instruction::Nop',
   'Instruction::ReturnUndefined',
   'assert!(!context.has_exception());')))

STAGE3F_TEST_BODY_HASHES = {('src/engine/code/binary_object/function_translate/capability.rs', 'ordinary_nop_is_the_exact_operand_free_raw177_row'): 'f75d3876877204f9b2a209216e5664095bab427ab1831db8ae7fdda946362b17',
 ('src/engine/code/binary_object/function_translate/mod.rs', 'operand_free_nop_translation_is_one_typed_operation'): '3fdd3855d14295ac08d90c15878eeb3a17afb2e9d5a6008182a0b0193cbd6ae4',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'lowers_representative_sanitized_operations_without_consulting_diagnostics'): 'fc152214094cc8dfa8f6e068f8f67a7a05ec3b88aa50dda9290a5970af0ad92a',
 ('src/engine/code/binary_object_publish.rs', 'ordinary_leaf_draft_ops_lower_one_for_one_without_reordering'): '5d1aba35fd5745d682ef784539053160d709ebc61224ae304559d8ce1097f772',
 ('src/engine/code/bytecode.rs', 'verifier_accepts_closed_non_terminating_control_flow'): '5bb41367aaa8ef961eef29717e74b246e0f4cda6bf3d6783ef470ca5cdd073b6',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_nop_preserves_exact_metadata_realm_and_zero_effect'): 'bab4e09fe90b483999fbe41f9a1bbf26724ce74834fa2faba1d8a1ece16bce82',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_nop_only_fallthrough_rolls_back_and_retries'): '110183deebf1bd2e02361b7302b2e033243a57a6b7d51c33ded2919eade36c7c',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_branch_targets_raw177_typed_index'): '4e0aa47698b6fd4bfe02e0dde0461251def3229450253d01b03fda139f554345'}
