"""Stage3B semantic ownership contracts and frozen runtime evidence.

S05 relocates synchronous callback algorithms to their shared Step/Resume owners.
Ordered payload checks below follow both request and reply; the published runtime
and oracle evidence below STAGE3B_RUNTIME_TEST_CONTRACTS remains frozen.
"""

STAGE3B_ORDERED_CONTRACTS = (('stage3b-validated-construction',
  'src/engine/heap/runtime/mod.rs',
  'prepare_constructor_pair',
  ('constructor: &CallableRef, new_target: &CallableRef,',
   'if !constructor.belongs_to(self) {',
   'if !self.is_constructor(constructor.as_object())? {',
   'if !new_target.belongs_to(self) {',
   'if !self.is_constructor(new_target.as_object())? {',
   'let constructor = ConstructorRef::from_validated_callable(constructor);',
   'let new_target = ConstructorRef::from_validated_callable(new_target);',
   'Ok(NativeConversion::Value((constructor, new_target)))')),
 ('stage3b-validated-construction',
  'src/engine/vm/call.rs',
  'construct_internal',
  ('self.prepare_constructor_pair(caller_realm, constructor, new_target)?',
   'NativeConversion::Throw(value) => return Ok(Completion::Throw(value)),',
   'self.construct_constructor_internal(caller_realm, &constructor, &new_target, arguments)')),
 ('stage3b-validated-construction',
  'src/engine/vm/entry.rs',
  'construct',
  ('runtime.prepare_constructor_pair(realm, constructor, new_target)? { '
   'NativeConversion::Value(pair) => pair, NativeConversion::Throw(value) => return '
   'Ok(Completion::Throw(value)),',
   'runtime.normalize_constructor(',
   'ConstructNewTarget::Validated(new_target)',
   'execute_root(runtime.clone(), realm, RootOperation::Construct(normalized))')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_value_with_raw_new_target_internal',
  ('let constructor = match self.constructor_from_value(caller_realm, function)?',
   'self.construct_constructor_with_raw_new_target_internal( caller_realm, &constructor, '
   'new_target, arguments, )')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_callable_with_raw_new_target_internal',
  ('constructor_from_value(caller_realm, Value::Object(constructor.as_object().clone()))?',
   'self.construct_constructor_with_raw_new_target_internal( caller_realm, &constructor, '
   'new_target, arguments, )')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_constructor_with_raw_new_target_internal',
  ('self.construct_internal_with_new_target( caller_realm, constructor, '
   'ConstructNewTarget::Raw(new_target), arguments, )',)),
 ('stage3b-validated-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_constructor_internal',
  ('self.construct_internal_with_new_target( caller_realm, constructor, '
   'ConstructNewTarget::Validated(new_target.clone()), arguments, )',)),
 ('stage3b-apply-order',
  'src/engine/vm/host_bridge.rs',
  'apply',
  ('let callable = self .runtime .callable_from_value(function.clone())',
   'if matches!(argument_array, Value::Undefined | Value::Null) {',
   '.call_internal(self.current_realm, &callable, this_or_new_target, &[])',
   'let arguments = match self.build_argument_list(argument_array)? {',
   'match kind {',
   'ApplyKind::Call => self .runtime .call_internal( self.current_realm, &callable, '
   'this_or_new_target, &arguments, )',
   'ApplyKind::Construct => self .runtime .construct_callable_with_raw_new_target_internal( '
   'self.current_realm, &callable, this_or_new_target, &arguments, )')),
 ('stage3b-function-realm',
  'src/engine/object/internal_methods.rs',
  'function_realm_from_value',
  ('self.0.state.borrow().heap.context(caller_realm)?;',
   'let Value::Object(object) = value else { return Ok(NativeConversion::Value(caller_realm)); };',
   'if !object.belongs_to(self) {',
   'self.function_realm_object_impl(Some(caller_realm), object.clone(), true)')),
 ('stage3b-function-realm',
  'src/engine/object/internal_methods.rs',
  'function_realm_object_impl',
  ('ObjectPayload::NativeFunction { data, .. } if data.realm.is_some() =>',
   'if allow_non_function && data.target.uses_calling_realm() {',
   'ObjectPayload::BytecodeFunction',
   'ObjectPayload::BoundFunction { target, .. } =>',
   'ObjectPayload::Proxy(data) =>',
   'if is_revoked {',
   'if allow_non_function {')),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseStep::start',
  ('NativeFunctionId::Promise(PromiseNativeKind::Constructor) =>',
   'let NativeInvocation::Construct { new_target } = invocation else',
   'runtime.callable_from_value(',
   'let __pending_field_new_target = new_target.clone();',
   'phase: Phase::ConstructorPrototype { executor }')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/promise/operation.rs',
  'prototype',
  ('let Phase::ConstructorPrototype { executor } = self.phase else',
   'let prototype = match result {',
   'NativeConversion::Throw(value) =>',
   'NativeConversion::Value(ConstructorPrototypeSource::Explicit(object)) => object,',
   'NativeConversion::Value(ConstructorPrototypeSource::Realm(realm)) =>',
   'runtime.promise_realm_data(realm)?.prototype,',
   'let promise = runtime.new_promise_object(&prototype)?;',
   'runtime.create_promise_resolving_functions(self.realm, &promise)?;',
   'let __pending_field_callable = executor;')),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'read',
  ('let data = runtime .proxy_snapshot_if_any(&proxy)?',
   'if data.is_revoked {',
   'let rooted = runtime.root_proxy_snapshot(&proxy, data)?;',
   'Ok(ProxyCallStep::request_read( rooted.handler.clone(), self.key.clone(), '
   'Value::Object(rooted.handler.clone()),',
   'phase: Phase::Method { rooted, search: self, }')),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'resume',
  ('let Phase::Method { rooted, mut search } = self.0.phase else',
   'let method = match completion {',
   'Completion::Throw(value) =>',
   'if !rooted.data.is_callable {',
   'if matches!(method, Value::Undefined | Value::Null) {',
   'if runtime.is_proxy_object(&rooted.target)? {',
   'search.depth = search.depth.saturating_add(1);',
   'return search.read(runtime, rooted.target);',
   'runtime.direct_call_target_from_value(Value::Object(rooted.target.clone()))?, search.receiver, '
   'search.arguments,',
   'let array = runtime.new_array_from_values(search.realm, search.arguments)?;',
   'let method = match runtime.direct_call_target_from_value(method) {',
   'method, Value::Object(rooted.handler.clone()), vec![ Value::Object(rooted.target.clone()), '
   'search.receiver, Value::Object(array), ],',
   'Ok(ProxyCallStep::request_call( target, receiver, arguments,',
   'phase: Phase::Result { _rooted: rooted, _guard: search.guard, }')),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods.rs',
  'call_proxy',
  ('let mut step = ProxyCallStep::start(self, realm, proxy.clone(), this_value, owned_arguments)?;',
   'ProxyCallStep::Complete(completion) => return Ok(completion),',
   'let completion = self.internal_get(realm, &object, &key, receiver)?;',
   'resume.resume(self, completion)? } } ProxyCallStep::Call',
   'self.call_internal(realm, &callable, receiver, &arguments)?',
   'self.call_proxy(realm, &proxy, receiver, &arguments)?',
   '}; resume.resume(self, completion)?')),
 ('stage3b-public-construction',
  'src/engine/api/context/calls.rs',
  'construct_with_new_target',
  ('constructor: &CallableRef',
   'new_target: &CallableRef',
   '.construct_internal(self.realm, constructor, new_target, arguments)')),
 ('stage3b-raw-construction',
  'src/engine/vm/call.rs',
  'normalize_constructor',
  ('mut constructor: ConstructorRef, mut new_target: ConstructNewTarget,',
   'match &new_target { ConstructNewTarget::Validated(target) if '
   '!target.as_object().belongs_to(self)',
   'ConstructNewTarget::Raw(value) => { self.validate_value_domain(value,',
   'if !self.is_constructor(constructor.as_object())? {',
   'if self.is_proxy_object(constructor.as_object())? {',
   'target: ConstructorTarget::Proxy(constructor), new_target, arguments,',
   'let callable = self.as_callable(constructor.as_object())?',
   'CallableExecution::Bound',
   'self.concatenate_bound_arguments(caller_realm, &bound, &arguments)?',
   'new_target.retarget_bound_identity(&constructor, &target);',
   'constructor = ConstructorRef::from_validated_callable(&target);',
   'target: ConstructorTarget::Ordinary { callable, classification, }, new_target, arguments,')),
 ('stage3b-raw-construction',
  'src/engine/vm/call.rs',
  'construct_internal_with_new_target',
  ('constructor: &ConstructorRef, new_target: ConstructNewTarget,',
   'self.normalize_constructor( caller_realm, constructor.clone(), new_target, arguments.to_vec(), '
   ')?',
   'ConstructorTarget::Proxy(constructor) => { return self.construct_proxy(caller_realm, '
   '&constructor, new_target, &arguments);',
   'CallableExecution::Native',
   'let execution_realm = if target.uses_calling_realm() { caller_realm } else { realm };',
   'return self.construct_native_function( &callable, execution_realm, target, min_readable_args, '
   'new_target.value(), &arguments, );',
   'CallableExecution::Bytecode',
   'ConstructorKind::Derived',
   'Value::Undefined, new_target.value(), &arguments,',
   'let raw_new_target = new_target.value();',
   'self.create_from_constructor_value(caller_realm, &raw_new_target)?',
   'this_value.clone(), raw_new_target, &arguments,')),
 ('stage3b-constructor-prototype',
  'src/engine/vm/call.rs',
  'constructor_prototype_source',
  ('prototype::finish( self, caller_realm, prototype::ProtoSourceStep::start(self, caller_realm, '
   'new_target.clone())?, )',)),
 ('stage3b-constructor-prototype',
  'src/engine/vm/call/prototype.rs',
  'ProtoSourceStep::start',
  ('new_target: Value,',
   'if matches!(new_target, Value::Undefined) {',
   'ConstructorPrototypeSource::Realm(realm),',
   'Ok(Self::ReadValue { receiver: new_target.clone(), key:',
   'resume: ProtoSourceResume(Box::new(ProtoSourceResumeState { realm, new_target })),')),
 ('stage3b-constructor-prototype',
  'src/engine/vm/call/prototype.rs',
  'ProtoSourceResume::resume',
  ('Completion::Throw(value) => NativeConversion::Throw(value),',
   'Completion::Return(Value::Object(prototype)) => { '
   'NativeConversion::Value(ConstructorPrototypeSource::Explicit(prototype))',
   'Completion::Return(_) => { match runtime.function_realm_from_value(self.0.realm, '
   '&self.0.new_target)? {',
   'NativeConversion::Value(realm) => { '
   'NativeConversion::Value(ConstructorPrototypeSource::Realm(realm))')),
 ('stage3b-constructor-prototype',
  'src/engine/vm/call/prototype.rs',
  'finish',
  ('ProtoSourceStep::ReadValue { receiver, key, resume, } => resume.resume( runtime, '
   'runtime.get_value_property_in_realm(realm, receiver, &key)?, )?',)),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'Search::read',
  ('proxy: ConstructorRef,',
   'runtime .proxy_snapshot_if_any(proxy.as_object())?',
   'if data.is_revoked {',
   'let rooted = runtime.root_proxy_snapshot(proxy.as_object(), data)?;',
   'Ok(ProxyConstructStep::request_read( rooted.handler.clone(), self.key.clone(),',
   'phase: Phase::Method { rooted, search: self, }')),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::resume',
  ('Completion::Return(value) if trap && !matches!(value, Value::Object(_)) =>',
   'let method = match completion {',
   '.constructor_from_value(search.realm, Value::Object(rooted.target.clone()))?',
   'if matches!(method, Value::Null | Value::Undefined) {',
   'if runtime.is_proxy_object(target.as_object())? {',
   'search.depth = search.depth.saturating_add(1);',
   'return search.read(runtime, target);',
   'Ok(ProxyConstructStep::request_construct( target, search.new_target, search.arguments,',
   'let array = runtime.new_array_from_values(search.realm, search.arguments)?;',
   'let method = match runtime.direct_call_target_from_value(method) {',
   'Ok(ProxyConstructStep::request_call( method, Value::Object(rooted.handler.clone()), vec![ '
   'Value::Object(rooted.target.clone()), Value::Object(array), search.new_target.value(), ],')),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods.rs',
  'construct_proxy',
  ('proxy: &ConstructorRef, new_target: ConstructNewTarget,',
   'construct::finish( self, realm, construct::ProxyConstructStep::start(',
   'self, realm, proxy.clone(), new_target, arguments.to_vec(),')),
 ('stage3b-public-construction',
  'src/engine/builtins/function/invoke.rs',
  'InvokeStep::start',
  ('if matches!(kind, InvokeKind::ReflectConstruct) {',
   'let new_target = if arguments.actual_arg_count > 2 {',
   'runtime.constructor_from_value(realm, value)?',
   'NativeConversion::Value(target) => ConstructNewTarget::Validated(target),',
   'let __pending_field_value = arguments.readable[1].clone();',
   'target: ForwardTarget::Construct { target: arguments.readable[0].clone(), new_target,')),
 ('stage3b-public-construction',
  'src/engine/builtins/function/invoke.rs',
  'InvokeResume::arguments',
  ('let arguments = match result {',
   'ForwardTarget::Construct { target, new_target } => {',
   'runtime.constructor_from_value(self.0.realm, target)?',
   'new_target.unwrap_or_else(|| ConstructNewTarget::Validated(target.clone()));',
   'InvokeStep::Construct(Box::new(InvokeConstruct { target, new_target, arguments,')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/typed_array/species.rs',
  'TypedSpeciesStep::create',
  ('arguments: Vec<Value>,',
   'if !runtime.is_constructor(&object)? {',
   'runtime.constructor_from_value(realm, Value::Object(object))?',
   'Ok(Self::Construct { constructor, arguments,',
   'phase: SpeciesPhase::Constructed(minimum_length),')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/build.rs',
  'BuildResume::construct',
  ('let constructor = std::mem::replace(&mut self.0.constructor, Value::Undefined);',
   'runtime.is_constructor(object)?',
   'runtime.constructor_from_value(self.0.realm, constructor)?',
   'Ok(BuildStep::request_construct( target, length.into_iter().collect(), self,')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/species.rs',
  'SpeciesResume::resume',
  ('if matches!(self.phase, Phase::Constructor) {',
   'runtime.is_constructor(object)?',
   'runtime.function_realm_from_value(self.realm, &constructor)?',
   'if constructor_realm != self.realm',
   'constructor = Value::Undefined; } } if let Value::Object(object) = constructor {',
   'self.phase = Phase::Species;',
   'key: PropertyKey::from(runtime.well_known_symbol(WellKnownSymbol::Species)),',
   'else if matches!(constructor, Value::Null) {',
   'if matches!(constructor, Value::Undefined) {',
   'runtime.constructor_from_value(self.realm, constructor)?',
   'NativeConversion::Value(target) => Ok(SpeciesStep::Construct { target, arguments: '
   'vec![Value::number(self.length as f64)],')),
 ('stage3b-native-prototype-family',
  'src/engine/vm/call.rs',
  'create_from_constructor_value',
  ('if matches!(new_target, Value::Undefined) {',
   'Completion::Return(Value::Undefined)',
   'self.get_value_property_in_realm(caller_realm, new_target.clone(), &key)?',
   'self.create_from_constructor_prototype_reply(caller_realm, new_target, reply)')),
 ('stage3b-native-prototype-family',
  'src/engine/vm/call.rs',
  'create_from_constructor_prototype_reply',
  ('Completion::Return(Value::Object(prototype)) => prototype,',
   'Completion::Return(_) => {',
   'self.function_realm_from_value(caller_realm, new_target)?',
   'heap.context(realm)?.object_prototype',
   'self.new_object(Some(&prototype))?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array/constructor.rs',
  'ConstructorStep::start',
  ('new_target: new_target.clone(),',
   'if matches!(new_target, Value::Undefined) {',
   'resume.resume(runtime, Completion::Return(Value::Undefined))',
   'Ok(Self::request_read( new_target.clone(),')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array/constructor.rs',
  'ConstructorResume::resume',
  ('Completion::Return(Value::Object(object)) => object,',
   'runtime.function_realm_from_value(self.0.realm, &self.0.new_target)?',
   '.context(realm)? .array_prototype',
   'runtime.new_empty_array_with_prototype(&prototype)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/function/dynamic.rs',
  'DynamicFunctionResume::resume',
  ('Phase::Eval => {',
   'if matches!(self.0.new_target, Value::Undefined) {',
   'self.0.value = value;',
   'let __pending_field_receiver = self.0.new_target.clone();',
   'Phase::Prototype => {',
   'if let Value::Object(object) = value',
   'runtime .function_realm_from_value(self.0.realm, &self.0.new_target)?',
   'state.heap.context(realm)?',
   'DynamicFunctionKind::Normal => context.function_prototype,',
   'DynamicFunctionKind::Generator => context.generator',
   'DynamicFunctionKind::Async => context.async_function',
   'DynamicFunctionKind::AsyncGenerator => context.async_generator',
   'runtime.set_prototype_of(&function, Some(&prototype))?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/primitive/constructor.rs',
  'PrimitiveConstructorResume::converted',
  ('if matches!(self.0.new_target, Value::Undefined) {',
   'self.0.value = value;',
   'let __pending_field_receiver = self.0.new_target.clone();')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/primitive/constructor.rs',
  'PrimitiveConstructorResume::resume',
  ('Completion::Return(Value::Object(object)) => object,',
   'runtime .function_realm_from_value(self.0.realm, &self.0.new_target)?',
   'runtime.primitive_prototype_for_realm(realm, self.0.kind)?',
   'runtime.new_primitive_object(&prototype, self.0.kind, self.0.value)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/date/constructor/operation.rs',
  'DateConstructorResume::prototype',
  ('self.0.phase = Phase::Prototype;',
   'let __pending_field_receiver = self.0.new_target.clone();')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/date/constructor/operation.rs',
  'DateConstructorResume::resume',
  ('Completion::Return(Value::Object(object)) => object,',
   'runtime.function_realm_from_value(self.0.realm, &self.0.new_target)?',
   '.context(realm)? .date_prototype',
   'runtime.new_date_object(&prototype, self.0.value)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/error/operation.rs',
  'ErrorStep::start',
  ('resume.new_target = if matches!(new_target, Value::Undefined) {',
   'let __pending_field_receiver = resume.new_target.clone();')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/error/operation.rs',
  'ErrorResume::resume',
  ('Phase::Prototype => {',
   'if let Value::Object(object) = value',
   'runtime .function_realm_from_value(self.0.realm, &self.0.new_target)?',
   'state.heap.context(realm)?',
   'context .error_prototype',
   'context.native_error_prototypes[kind.index()]',
   'self.0.object = Some(runtime.new_error_object(&prototype)?);')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/constructor.rs',
  'BufferConstructorResume::lookup',
  ('new_target: self.0.new_target.clone(),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/constructor.rs',
  'BufferConstructorResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'runtime.shared_array_buffer_default_prototype(realm)?',
   'runtime.array_buffer_default_prototype(realm)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/constructor.rs',
  'finish',
  ('ProtoSourceStep::start(runtime, realm, new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/data_view.rs',
  'DataViewConstructorResume::lookup',
  ('new_target: self.0.new_target.clone(),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/data_view.rs',
  'DataViewConstructorResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'runtime.data_view_default_prototype(realm)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/data_view.rs',
  'finish_constructor',
  ('ProtoSourceStep::start(runtime, realm, new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/typed_array/create.rs',
  'TypedCreateStep::constructor',
  ('Self::request_prototype( new_target.clone(),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/typed_array/create.rs',
  'TypedCreateResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'runtime.typed_array_default_prototype(realm, element)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/typed_array/create.rs',
  'finish',
  ('ProtoSourceStep::start(runtime, realm, new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/regexp/constructor.rs',
  'RegExpConstructorResume::lookup',
  ('new_target: self.0.new_target.clone(),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/regexp/constructor.rs',
  'RegExpConstructorResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'runtime.regexp_realm_data(realm)?.prototype,')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/regexp/constructor.rs',
  'finish_constructor',
  ('ProtoSourceStep::start(runtime, realm, new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/collection.rs',
  'CollectionStep::start',
  ('let __pending_field_new_target = new_target.clone();',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/collection.rs',
  'CollectionResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'CollectionKind::Map => runtime.map_realm_data(realm)?.prototype,',
   'CollectionKind::Set => runtime.set_realm_data(realm)?.prototype,',
   'runtime.weak_collection_prototype(realm, WeakCollectionKind::Map)?',
   'runtime.weak_collection_prototype(realm, WeakCollectionKind::Set)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/collection.rs',
  'finish',
  ('runtime.constructor_prototype_source(realm, &new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/constructor.rs',
  'ConstructorStep::start',
  ('new_target: Value::Object(new_target.clone()),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/constructor.rs',
  'ConstructorResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   '.context(realm)? .iterator_prototype')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/constructor.rs',
  'finish',
  ('runtime.constructor_prototype_source(realm, &new_target)?',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/weak_ref/constructor.rs',
  'WeakConstructorStep::start',
  ('new_target: new_target.clone(),',)),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/weak_ref/constructor.rs',
  'WeakConstructorResume::prototype',
  ('ConstructorPrototypeSource::Explicit(',
   'ConstructorPrototypeSource::Realm(realm)',
   'runtime.weak_intrinsic_prototype(realm, kind)?')),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/weak_ref/constructor.rs',
  'finish',
  ('ProtoSourceStep::start(runtime, realm, new_target)?',)),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/slice.rs',
  'BufferSliceResume::resume',
  ('Phase::Constructor { start, count } => {',
   'if matches!(value, Value::Undefined) {',
   'let Value::Object(object) = value else {',
   'key: PropertyKey::from(runtime.well_known_symbol(WellKnownSymbol::Species)),',
   'let updated_0 = Phase::Species { start, count }; self.0.phase = updated_0;',
   'Phase::Species { start, count } => {',
   'if matches!(value, Value::Undefined | Value::Null) {',
   'runtime.constructor_from_value(self.0.realm, value)?',
   'arguments.push(Value::Int( i32::try_from(count).expect( ), ));',
   'Ok(BufferSliceStep::Construct { constructor, arguments,')),
 ('stage3b-species-constructor',
  'src/engine/builtins/regexp/species.rs',
  'RegExpSpeciesStep::start',
  ('runtime.regexp_realm_data(realm)?.constructor;',
   'ConstructorRef::from_validated_object(',
   'Ok(Self::Read { object: regexp,',
   'resume: RegExpSpeciesResume(Box::new(RegExpSpeciesResumeState { realm, default, species: '
   'false,')),
 ('stage3b-species-constructor',
  'src/engine/builtins/regexp/species.rs',
  'RegExpSpeciesResume::resume',
  ('if self.0.species {',
   'if matches!(value, Value::Null | Value::Undefined) {',
   'NativeConversion::Value(self.0.default)',
   'else if !matches!(value, Value::Object(_)) {',
   'runtime.constructor_from_value(self.0.realm, value)?',
   'if matches!(value, Value::Undefined) {',
   'let Value::Object(object) = value else {',
   'key: PropertyKey::from(runtime.well_known_symbol(WellKnownSymbol::Species)),',
   'let updated_0 = true; self.0.species = updated_0;')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/typed_array/species.rs',
  'finish_species',
  ('TypedSpeciesStep::Construct { constructor, arguments, resume, } => resume.resume( runtime, '
   'runtime.construct_constructor_internal( realm, &constructor, &constructor, &arguments, )?, '
   ')?',)),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/build.rs',
  'finish',
  ('BuildStep::Construct { mut resume } => { let target = resume.take_construct_target(); let '
   'arguments = resume.take_construct_arguments(); resume.resume( runtime, '
   'runtime.construct_constructor_internal(realm, &target, &target, &arguments)?, )?',)),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/species.rs',
  'finish',
  ('SpeciesStep::Construct { target, arguments } => { return '
   'runtime.construct_constructor_internal(realm, &target, &target, &arguments);',)))


# Constructor-only capability is carried by the request, not a CallableRef
# hidden in its producer's return type after the S05 split.
CONSTRUCTION_CAPABILITIES = (
 ('stage3b-proxy-construct-order', 'src/engine/object/internal_methods/construct.rs', 'struct:ProxyConstructStepPending',
  'construct_target: Option<ConstructorRef>, construct_new_target: Option<ConstructNewTarget>, construct_arguments: Option<Vec<Value>>,'),
 ('stage3b-public-construction', 'src/engine/builtins/function/invoke.rs', 'struct:InvokeConstruct',
  'pub(crate) target: ConstructorRef, pub(crate) new_target: ConstructNewTarget, pub(crate) arguments: Vec<Value>,'),
 ('stage3b-species-constructor', 'src/engine/builtins/array/build.rs', 'struct:BuildStepPending',
  'construct_target: Option<ConstructorRef>, construct_arguments: Option<Vec<Value>>,'),
 ('stage3b-species-constructor', 'src/engine/builtins/array/species.rs', 'SpeciesStep',
  'Construct { target: ConstructorRef, arguments: Vec<Value>,'),
 ('stage3b-species-constructor', 'src/engine/builtins/array_buffer/typed_array/species.rs', 'TypedSpeciesStep',
  'Construct { constructor: ConstructorRef, arguments: Vec<Value>,'),
 ('stage3b-species-constructor', 'src/engine/builtins/array_buffer/slice.rs', 'BufferSliceStep',
  'Construct { constructor: ConstructorRef, arguments: Vec<Value>,'),
 ('stage3b-species-constructor', 'src/engine/builtins/regexp/species.rs', 'RegExpSpeciesStep',
  'Complete(NativeConversion<ConstructorRef>),'),
)

# S06 migrated the last synchronous prototype helper to PromiseStep/Resume.

CONSTRUCTOR_ONLY_ITEMS = (('stage3b-proxy-construct-order', 'src/engine/object/internal_methods/construct.rs', 'Search::read'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::resume'),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/typed_array/species.rs',
  'TypedSpeciesStep::create'),
 ('stage3b-species-constructor', 'src/engine/builtins/array/build.rs', 'BuildResume::construct'),
 ('stage3b-species-constructor', 'src/engine/builtins/array/species.rs', 'SpeciesResume::resume'),
 ('stage3b-species-constructor', 'src/engine/builtins/array_buffer/slice.rs', 'BufferSliceResume::resume'),
 ('stage3b-species-constructor', 'src/engine/builtins/regexp/species.rs', 'RegExpSpeciesResume::resume'))

SPECIES_FUNCTIONS = (('src/engine/builtins/promise.rs', 'promise_species_constructor', True),)

STAGE3B_RUNTIME_TEST_CONTRACTS = (('trusted_quickjs_ordinary_apply_admits_only_canonical_typed_kinds',
  ('for (magic, expected_kind) in [(0, ApplyKind::Call), (1, ApplyKind::Construct)] {',
   'for magic in [2_u16, u16::MAX] {',
   'assert_eq!(runtime.heap_counts(), baseline);')),
 ('trusted_quickjs_ordinary_apply_preserves_object_list_call_and_construct_semantics',
  ('&[target, receiver, list]',
   '&[constructor, new_target.clone(), list]',
   'context.get_property(&instance, &sum).unwrap()')),
 ('trusted_quickjs_ordinary_apply_nullish_lists_use_raw_receiver_for_both_kinds',
  ('assert!(!runtime.is_constructor(target_object).unwrap());',
   'for magic in [0_u8, 1] {',
   'for argument_array in [Value::Null, Value::Undefined] {')),
 ('trusted_quickjs_ordinary_apply_preserves_error_order_realm_and_pending_identity',
  ('native_error_prototypes[NativeErrorKind::Type.index()]',
   'caller.take_exception().unwrap().unwrap()',
   '&[target, receiver.clone(), Value::Null]')),
 ('trusted_quickjs_ordinary_apply_raw_prototype_get_preserves_order_and_receiver',
  ('Value::Int(17), empty.clone()',
   'context.take_exception().unwrap().unwrap()',
   'Some(context.object_prototype().unwrap())')),
 ('trusted_quickjs_ordinary_apply_construct_preserves_raw_new_target_across_dispatch',
  ('NativeFunctionId::ConstructorProbe',
   'set_constructor_bit(native.as_object(), true)',
   'Value::Int(17), empty.clone()')),
 ('construct_only_proxy_and_new_target_do_not_require_call_capability',
  ('runtime.as_callable(&proxy).unwrap().is_none()',
   'VmHost::construct(',
   'runtime.set_constructor_bit(&new_target, true)')),
 ('trusted_quickjs_ordinary_apply_raw_calling_realm_functions_fall_back_to_the_caller',
  ('execute_pending_job()',
   'Some(caller.realm)',
   'runtime.set_constructor_bit(&revoke_object, false)')),
 ('trusted_quickjs_ordinary_apply_raw_native_constructors_use_class_fallbacks',
  ('NativeFunctionId::ArrayConstructor',
   'for (label, constructor_source, arguments_source) in cases {',
   'Some(expected_prototype)')),
 ('trusted_quickjs_ordinary_apply_verifies_stack_and_reindexed_branch_targets',
  ('const UNDERFLOW: &str',
   'for (label, code, max_stack, expected) in [',
   'Instruction::Goto(9)',
   'Instruction::Apply(ApplyKind::Call)')))

STAGE3C_TEST_MODULE_CONTRACTS = (('src/engine/heap/runtime/mod.rs', ';'),
 ('src/engine/vm/mod.rs', '{'),
 ('src/engine/code/bytecode.rs', '{'),
 ('src/engine/code/binary_object/function_translate/mod.rs', '{'),
 ('src/engine/code/binary_object/ordinary_leaf.rs', '{'),
 ('src/engine/code/binary_object_publish.rs', '{'),
 ('src/engine/code/binary_object/function_translate/capability.rs', '{'))

STAGE3C_REQUIRED_TEST_SOURCES = {'src/engine/code/bytecode.rs',
 'src/engine/code/binary_object/function_translate/capability.rs',
 'src/engine/code/binary_object/function_translate/mod.rs',
 'src/engine/code/binary_object/ordinary_leaf.rs',
 'src/engine/code/binary_object_publish.rs',
 'src/engine/heap/runtime/tests.rs',
 'src/engine/vm/mod.rs'}

STAGE3C_TEST_CONTRACTS = (('src/engine/code/binary_object/function_translate/capability.rs',
  'registry_locks_the_current_physical_cohorts',
  ('(110, 1, 104, 29)',
   'assert_eq!(ordinary_only + shared, 133);',
   'assert_eq!(scalar_only + ordinary_only + shared, 134);')),
 ('src/engine/code/binary_object/function_translate/capability.rs',
  'ordinary_invocation_addition_is_the_exact_reviewed_six_row_set',
  ('(35, OpcodeFormat::NPop, Recipe::TailCall)',
   '(37, OpcodeFormat::NPop, Recipe::TailCallMethod)',
   'CapabilityPolicy::OrdinaryOnly(expected_recipe)')),
 ('src/engine/code/binary_object/function_translate/capability.rs',
  'blocked_frontier_has_stable_typed_category_counts',
  ('let mut counts = [0_usize; 15];',
   'assert!(counts.into_iter().all(|count| count != 0));',
   'assert_eq!(counts.into_iter().sum::<usize>(), 110);')),
 ('src/engine/code/binary_object/function_translate/mod.rs',
  'tail_invocation_lowering_preserves_the_npop_operand_and_kind',
  ('NativeOperands::NPop(u16::MAX)',
   '(false, FunctionOp::TailCall(u16::MAX))',
   '(true, FunctionOp::TailCallMethod(u16::MAX))')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'tail_invocation_operands_reach_the_ordinary_dto_unchanged',
  ('FunctionOp::TailCall(u16::MAX)',
   'OrdinaryLeafOp::TailCall(u16::MAX)',
   'OrdinaryLeafOp::TailCallMethod(u16::MAX)')),
 ('src/engine/code/binary_object_publish.rs',
  'ordinary_tail_invocation_publishes_one_for_one_with_the_unchanged_operand',
  ('OrdinaryLeafOp::TailCall(u16::MAX)',
   'Instruction::TailCall(u16::MAX)',
   'Instruction::TailCallMethod(u16::MAX)',
   'assert_eq!(next_synthetic_index, 0);')),
 ('src/engine/code/bytecode.rs',
  'verifier_models_tail_invocations_as_terminal_zero_result_operations',
  ('Instruction::TailCall(2)',
   'Instruction::TailCallMethod(2)',
   'for instruction in [Instruction::TailCall(0), Instruction::TailCallMethod(0)]',
   'Instruction::TailCall(u16::MAX)',
   'Instruction::TailCallMethod(u16::MAX)')),
 ('src/engine/vm/mod.rs',
  'tail_invocations_complete_the_frame_with_exact_call_operands',
  ('Completion::Return(Value::Int(42))',
   'Value::Undefined, vec![Value::Int(11), Value::Int(12)]',
   'Value::Int(21), Value::Int(20), vec![Value::Int(22), Value::Int(23)]')),
 ('src/engine/vm/mod.rs',
  'tail_invocation_throws_use_the_activation_backtrace_and_catch_path',
  ('Completion::Throw(Value::Int(77))',
   'assert_eq!(host.backtrace_values, [Value::Int(77)]);',
   'assert_eq!(host.captured_local_reuse_preparations, 1);',
   'Completion::Throw(Value::Int(88))')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_invocations_use_exact_bc5_wires_and_semantics',
  ('assert_eq!(QUICKJS_ORDINARY_TAIL_CALL_BC5.len(), 57);',
   '0x8ff9_d2c1_0c7e_2228',
   'assert_eq!(QUICKJS_ORDINARY_TAIL_CALL_METHOD_BC5.len(), 62);',
   '0xe87d_54c0_a2a1_40ca',
   'Instruction::TailCall(2)',
   'Instruction::TailCallMethod(2)')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_invocation_failures_are_recoverable',
  ('vec![Value::Int(0), Value::Int(1), Value::Int(2)]',
   'vec![Value::Null, Value::Int(0), Value::Int(1), Value::Int(2)]',
   'Err(RuntimeError::Exception)',
   'Value::Int(42)')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_verification_rolls_back_heap_and_atoms',
  ('quickjs_ordinary_three_argument_with_code(&[0x23, 0xff, 0xff], 0)',
   'quickjs_ordinary_four_argument_with_code(&[0x25, 0xff, 0xff], 0)',
   'assert_eq!(runtime.heap_counts(), baseline',
   'assert_eq!(runtime.test_atom_count(), baseline_atoms')),
 ('src/engine/heap/runtime/tests.rs',
  'published_tail_call_uses_backtrace_and_current_activation_catch_semantics',
  ('Instruction::TailCall(0)',
   'let stack = own_stack_string(&runtime, &error).to_utf8_lossy();',
   'Instruction::Catch(4)',
   'Value::Int(17)')))

STAGE3C_TEST_BODY_HASHES = {('src/engine/code/binary_object/function_translate/capability.rs', 'registry_locks_the_current_physical_cohorts'): '1c74d3733c3b55d08359e7c3b9a9f76babb0f59f841c4306311a054dba0f1b00',
 ('src/engine/code/binary_object/function_translate/capability.rs', 'ordinary_invocation_addition_is_the_exact_reviewed_six_row_set'): '0bd25bc945bde404ea911c720491e06a0d58c7257683347372b6c74843d3afc2',
 ('src/engine/code/binary_object/function_translate/capability.rs', 'blocked_frontier_has_stable_typed_category_counts'): 'f2d596485d43e0c5ca2a0c77e5f332b893c54dfa6cfdbfc2367a476bd2071ec2',
 ('src/engine/code/binary_object/function_translate/mod.rs', 'tail_invocation_lowering_preserves_the_npop_operand_and_kind'): 'f9a36b2d07545f80276edce3e1e7f3e1baaa56fcdfd82996a857be1958acccd2',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'tail_invocation_operands_reach_the_ordinary_dto_unchanged'): 'fd78ceeb26a50bc988ebb4fdece4f4417b89abd31bbfe0edae6480899e8c1ecc',
 ('src/engine/code/binary_object_publish.rs', 'ordinary_tail_invocation_publishes_one_for_one_with_the_unchanged_operand'): '7277c89d2d824c8bfe59cecc5ed5fdbf4e68f0368b719794d3072df7782bc94e',
 ('src/engine/code/bytecode.rs', 'verifier_models_tail_invocations_as_terminal_zero_result_operations'): '67b24ba74d50030e6dacc306fc68641ba838e33abad42388209c53a080d26915',
 ('src/engine/vm/mod.rs', 'tail_invocations_complete_the_frame_with_exact_call_operands'): '0745b22ec76c903693df4dcd2380646a1846204a005c5e595dfcb4054a4d4f53',
 ('src/engine/vm/mod.rs', 'tail_invocation_throws_use_the_activation_backtrace_and_catch_path'): '55580f9eaaced1ad6733f50126d885d34ac1944ca6e6d5f889a98e4699abd82c',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_invocations_use_exact_bc5_wires_and_semantics'): '4b972572d236f13acf54b98365cd4c8ad52bd86e5a9dc97cbb67b727a8540562',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_invocation_failures_are_recoverable'): '0640226781baa7b22b4a68b2c1d0929ee1c60e09c347c1ebd9f23ed21bfd6235',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_verification_rolls_back_heap_and_atoms'): 'e089f00738beddf2de2926d27f59850eb34b4a806184177deb9922228a0cc767',
 ('src/engine/heap/runtime/tests.rs', 'published_tail_call_uses_backtrace_and_current_activation_catch_semantics'): '898b42586dcc7d3a094d4146650a6536614e400103d580a9ee2f652592ab7508'}


# S11 resident request builders replace the previously pinned inline payloads.
# Same-named owner slots and return routing were reviewed before pinning.
STAGE3B_RESIDENT_TRANSPORT_HASHES = (('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseStep::request_prototype',
  'ad5c1401b985095fe2f1144e95a68a5b033603138b0878dc877e9ffce917e968'),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseResume::take_prototype_new_target',
  '5a48654d00029908c3e1a3fad91a764186d92926332c8ae6bc393bc75b355b50'),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseStep::request_call',
  '42f220939767bec3cdf098fc99c05983cb3e03873db4c68b93a4e92c321dd4e6'),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseResume::take_call_callable',
  '12fc6094b03ac3b2df7392712df4c875eed1ebc8d5b3c400ab4776dfa7cd91ba'),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseResume::take_call_receiver',
  '16b6aa2d1b68c65b54e087ae720d306f3f052d87a6f98617f0e7900ebbc2539c'),
 ('stage3b-promise-constructor',
  'src/engine/builtins/promise/operation.rs',
  'PromiseResume::take_call_arguments',
  'ff353e0b54316b642b4cc372530f7cbbf7eca19a0dc1fad3d34829172415a761'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallStep::request_read',
  'b247d9c63bef7e9398676184fcd4f55b8e8c67df3daba0eac3f3c9dffba02df7'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_read_object',
  '5be8711da5102cc8e6a3783d54f62b763e0cb6bb7c5f1c5c009149f938051819'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallStep::request_call',
  'e032fc86d2ff0e8f9c523aa7ac2e3d8eaece697f56d3d6b34b89a0062e5f1862'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_call_target',
  'd73235a03c99ebc681fdaf2e7e9a6138a1832228f80cf3b50d10f7a72bba1b33'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_call_receiver',
  '89276aef1730d8555cc37dd1835fadef95fdefcbc69bbe2b95810a600ae96c11'),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods/call.rs',
  'ProxyCallResume::take_call_arguments',
  '8c9f7e830bde51955ab37842599ec280841bcf53f5d7018bbf3b3ca263eeb5b7'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructStep::request_read',
  'dfcb4b1c4ea149c53b4cbe693810e07e0c3451a0715a613579e7db319a5fedbe'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_read_object',
  '5be8711da5102cc8e6a3783d54f62b763e0cb6bb7c5f1c5c009149f938051819'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructStep::request_construct',
  '53b371bff65ee16f52df8acc529c86d175320dc343740ee36bebbe393dc6f7a9'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_construct_target',
  '59bb2e59303317c77348995c7bc2917242e9fab7927b73815e9ef1549f194f1b'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_construct_new_target',
  'e36d2bb347eb39cb9380397901b74abb2a24117903d1607c8659a7ba6edf578d'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_construct_arguments',
  '8826968006e1afca91de44025a5731f233b1154223ef540deca3e2ffa7552cbc'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructStep::request_call',
  'a09e7ea079ebef2862b8ea3bba027860200ed064b8a1057c5662d3f7d81d37c9'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_call_target',
  'd73235a03c99ebc681fdaf2e7e9a6138a1832228f80cf3b50d10f7a72bba1b33'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_call_receiver',
  '89276aef1730d8555cc37dd1835fadef95fdefcbc69bbe2b95810a600ae96c11'),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods/construct.rs',
  'ProxyConstructResume::take_call_arguments',
  '8c9f7e830bde51955ab37842599ec280841bcf53f5d7018bbf3b3ca263eeb5b7'),
 ('stage3b-public-construction',
  'src/engine/builtins/function/invoke.rs',
  'InvokeStep::request_arguments',
  '9b0a459b60ee1b089a685274191ea929b67fffabe0315ad3c06a2c8494e94dea'),
 ('stage3b-public-construction',
  'src/engine/builtins/function/invoke.rs',
  'InvokeResume::take_arguments_value',
  '50c1f6d9a957e45a797abc25d35d12273392d05bc137542ba3abcba2a70ffd3a'),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/build.rs',
  'BuildStep::request_construct',
  '527749df4c0fc8b2bda9d7ff01e66f49ca9917a8b1fc245f7e5ede2ae26a59ac'),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/build.rs',
  'BuildResume::take_construct_target',
  '59bb2e59303317c77348995c7bc2917242e9fab7927b73815e9ef1549f194f1b'),
 ('stage3b-species-constructor',
  'src/engine/builtins/array/build.rs',
  'BuildResume::take_construct_arguments',
  '8826968006e1afca91de44025a5731f233b1154223ef540deca3e2ffa7552cbc'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array/constructor.rs',
  'ConstructorStep::request_read',
  'b248b7a140b64e13671cf7e15fb6789b5d623ecd846aed508614ea18c748a4b8'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array/constructor.rs',
  'ConstructorResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array/constructor.rs',
  'ConstructorResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/function/dynamic.rs',
  'DynamicFunctionStep::request_read',
  'c2f6382b2c70f42b956a75b4bdec3693c7dab50299217fb56d6a542e9eb4724d'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/function/dynamic.rs',
  'DynamicFunctionResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/function/dynamic.rs',
  'DynamicFunctionResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/primitive/constructor.rs',
  'PrimitiveConstructorStep::request_read',
  'beb9a009630e4d7befb5c9e65456925012c0fc5feb73aade1e1c5b7635d6e9d5'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/primitive/constructor.rs',
  'PrimitiveConstructorResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/primitive/constructor.rs',
  'PrimitiveConstructorResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/date/constructor/operation.rs',
  'DateConstructorStep::request_read',
  'bf4d975d7d8c9a1fd76fd70b56a0b948cbfa9e0c5fb5b217193c97ecec80abec'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/date/constructor/operation.rs',
  'DateConstructorResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/date/constructor/operation.rs',
  'DateConstructorResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/error/operation.rs',
  'ErrorStep::request_read',
  '7f34a21a5c0bdde3e32696a732ef80579651db6723f341e2669a17d38781aa79'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/error/operation.rs',
  'ErrorResume::take_read_receiver',
  '7eb0a4ac568289e02a0b34d0326809cfb4af55ccdb95467d1b55ab48b3b1bb8e'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/error/operation.rs',
  'ErrorResume::take_read_key',
  'edccb7310162831d27960b18bedead60946b0be325f559d279022106654b247c'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/typed_array/create.rs',
  'TypedCreateStep::request_prototype',
  '278f00e79adcc946704c2985038b6adbd96a9a1e276fda4cda8831451b56a3ef'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/array_buffer/typed_array/create.rs',
  'TypedCreateResume::take_prototype_new_target',
  'bcb1a2370c9418a1e7596d68aa77191f2b87e458b1a54344c4a5ed76f703f2b5'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/collection.rs',
  'CollectionStep::request_prototype',
  '0dc2ac46191a2a135bab9febc507716b2ec758394ee50024d50ec108b1ccbe86'),
 ('stage3b-native-prototype-family',
  'src/engine/builtins/iterator/collection.rs',
  'CollectionResume::take_prototype_new_target',
  'bcb1a2370c9418a1e7596d68aa77191f2b87e458b1a54344c4a5ed76f703f2b5'))
