"""Pinned data and expected shapes for runtime_contracts."""

STAGE3B_ORDERED_CONTRACTS = (('stage3b-validated-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_internal',
  ('constructor: &CallableRef, new_target: &CallableRef,',
   'if !constructor.belongs_to(self) {',
   'if !self.is_constructor(constructor.as_object())? {',
   'if !new_target.belongs_to(self) {',
   'if !self.is_constructor(new_target.as_object())? {',
   'let constructor = ConstructorRef::from_validated_callable(constructor);',
   'let new_target = ConstructorRef::from_validated_callable(new_target);',
   'self.construct_constructor_internal(caller_realm, &constructor, &new_target, arguments)')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_internal_with_new_target',
  ('constructor: &ConstructorRef, new_target: ConstructNewTarget,',
   'match &new_target { ConstructNewTarget::Validated(new_target) =>',
   'ConstructNewTarget::Raw(new_target) => { self.validate_value_domain(new_target,',
   'if !self.is_constructor(constructor.as_object())? {',
   'if self.is_proxy_object(constructor.as_object())? { return self.construct_proxy(caller_realm, '
   '&constructor, new_target, &arguments); }',
   'let callable = self.as_callable(constructor.as_object())?',
   'CallableExecution::Bound',
   'new_target.retarget_bound_identity(&constructor, &target);',
   'constructor = ConstructorRef::from_validated_callable(&target);',
   'CallableExecution::Native',
   'let execution_realm = if target.uses_calling_realm() { caller_realm } else { realm };',
   'return self.construct_native_function( &callable, execution_realm, target, min_readable_args, '
   'new_target.value(), &arguments, );',
   'CallableExecution::Bytecode',
   'ConstructorKind::Derived',
   'Value::Undefined, new_target.value(), &arguments,',
   'let raw_new_target = new_target.value();',
   'self.create_from_constructor_value(caller_realm, &raw_new_target)?',
   'this_value.clone(), raw_new_target, &arguments,',
   'CallableExecution::Proxy')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_value_with_raw_new_target_internal',
  ('let constructor = match self.constructor_from_value(caller_realm, function)?',
   'self.construct_constructor_with_raw_new_target_internal( caller_realm, &constructor, '
   'new_target, arguments, )')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_callable_with_raw_new_target_internal',
  ('constructor_from_value(caller_realm, Value::Object(constructor.as_object().clone()))?',
   'self.construct_constructor_with_raw_new_target_internal( caller_realm, &constructor, '
   'new_target, arguments, )')),
 ('stage3b-raw-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_constructor_with_raw_new_target_internal',
  ('self.construct_internal_with_new_target( caller_realm, constructor, '
   'ConstructNewTarget::Raw(new_target), arguments, )',)),
 ('stage3b-validated-construction',
  'src/engine/heap/runtime/mod.rs',
  'construct_constructor_internal',
  ('self.construct_internal_with_new_target( caller_realm, constructor, '
   'ConstructNewTarget::Validated(new_target.clone()), arguments, )',)),
 ('stage3b-apply-order',
  'src/engine/vm/host_bridge.rs',
  'apply',
  ('let callable = self .runtime .callable_from_value(function.clone())',
   'if matches!(argument_array, Value::Undefined | Value::Null) {',
   '.call_internal(self.current_realm, &callable, this_or_new_target, &[])',
   'let arguments = match self.build_argument_list(argument_array)? {',
   'match kind {',
   'ApplyKind::Call => self .runtime .call_internal( self.current_realm, &callable, '
   'this_or_new_target, &arguments, )',
   'ApplyKind::Construct => self .runtime .construct_callable_with_raw_new_target_internal( '
   'self.current_realm, &callable, this_or_new_target, &arguments, )')),
 ('stage3b-function-realm',
  'src/engine/object/internal_methods.rs',
  'function_realm_from_value',
  ('self.0.state.borrow().heap.context(caller_realm)?;',
   'let Value::Object(object) = value else { return Ok(NativeConversion::Value(caller_realm)); };',
   'if !object.belongs_to(self) {',
   'self.function_realm_object_impl(Some(caller_realm), object.clone(), true)')),
 ('stage3b-function-realm',
  'src/engine/object/internal_methods.rs',
  'function_realm_object_impl',
  ('ObjectPayload::NativeFunction { data, .. } if data.realm.is_some() =>',
   'if allow_non_function && data.target.uses_calling_realm() {',
   'ObjectPayload::BytecodeFunction',
   'ObjectPayload::BoundFunction { target, .. } =>',
   'ObjectPayload::Proxy(data) =>',
   'if is_revoked {',
   'if allow_non_function {')),
 ('stage3b-constructor-prototype',
  'src/engine/heap/runtime/mod.rs',
  'constructor_prototype_source',
  ('if matches!(new_target, Value::Undefined) {',
   'let prototype = match self.get_value_property_in_realm( caller_realm, new_target.clone(), '
   '&prototype_key, )? {',
   'if let Value::Object(prototype) = prototype {',
   'self.function_realm_from_value(caller_realm, new_target) .map(|result| match result {',
   'NativeConversion::Value(realm) => { '
   'NativeConversion::Value(ConstructorPrototypeSource::Realm(realm)) }')),
 ('stage3b-constructor-prototype',
  'src/engine/heap/runtime/mod.rs',
  'prototype_from_constructor_value',
  ('match self.constructor_prototype_source(caller_realm, new_target)? {',
   'ConstructorPrototypeSource::Explicit(prototype)',
   'ConstructorPrototypeSource::Realm(realm)',
   'fallback(realm).map(NativeConversion::Value)',
   'NativeConversion::Throw(value) => Ok(NativeConversion::Throw(value))')),
 ('stage3b-proxy-call-order',
  'src/engine/object/internal_methods.rs',
  'call_proxy',
  ('let data = self .proxy_snapshot_if_any(&current)?',
   'if data.is_revoked {',
   'let rooted = self.root_proxy_snapshot(&current, data)?;',
   'let method = match self.internal_get(',
   'if !rooted.data.is_callable {',
   'if matches!(method, Value::Undefined | Value::Null) {',
   'if self.is_proxy_object(&rooted.target)? {',
   'current = rooted.target.clone();',
   'depth = depth.saturating_add(1);',
   'continue;',
   'return self.call_value_internal( realm, Value::Object(rooted.target.clone()), this_value, '
   'arguments, );',
   'let argument_array = self.new_array_from_values(realm, arguments.to_vec())?;',
   'let method = match self.direct_call_target_from_value(method) {',
   '&[ Value::Object(rooted.target.clone()), this_value, Value::Object(argument_array), ],')),
 ('stage3b-proxy-construct-order',
  'src/engine/object/internal_methods.rs',
  'construct_proxy',
  ('proxy: &ConstructorRef, new_target: ConstructNewTarget,',
   'let data = self.proxy_snapshot_if_any(current.as_object())?',
   'if data.is_revoked {',
   'let rooted = self.root_proxy_snapshot(current.as_object(), data)?;',
   'let method = match self.internal_get(',
   'let target = match self.constructor_from_value(realm, Value::Object(rooted.target.clone()))?',
   'if matches!(method, Value::Undefined | Value::Null) {',
   'if self.is_proxy_object(target.as_object())? {',
   'current = target;',
   'depth = depth.saturating_add(1);',
   'continue;',
   '.construct_internal_with_new_target(realm, &target, new_target, arguments);',
   'let argument_array = self.new_array_from_values(realm, arguments.to_vec())?;',
   'let method = match self.direct_call_target_from_value(method) {',
   'let result = self.call_proxy_trap(',
   '&[ Value::Object(rooted.target.clone()), Value::Object(argument_array), new_target.value(), ],',
   'return match result {')),
 ('stage3b-public-construction',
  'src/engine/api/context/calls.rs',
  'construct_with_new_target',
  ('constructor: &CallableRef',
   'new_target: &CallableRef',
   '.construct_internal(self.realm, constructor, new_target, arguments)')),
 ('stage3b-public-construction',
  'src/engine/builtins/reflect.rs',
  'call_reflect_construct',
  ('let explicit_new_target = if arguments.actual_arg_count > 2 {',
   'self.constructor_from_value(realm, value)?',
   'let forwarded = match self.build_array_like_argument_list(',
   'let target = match self.constructor_from_value(realm, target_value)?',
   'let new_target = explicit_new_target.unwrap_or_else(|| target.clone());',
   'self.construct_constructor_internal(realm, &target, &new_target, &forwarded)')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/typed_array/species.rs',
  'typed_array_create_from_constructor_arguments',
  ('if !self.is_constructor(&object)? {',
   'let constructor = match self.constructor_from_value(realm, Value::Object(object))?',
   'let target = match self.construct_constructor_internal( realm, &constructor, &constructor, '
   'arguments, )? {')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array.rs',
  'array_from_result',
  ('let constructor = match self.constructor_from_value(realm, constructor)?',
   'let arguments = length.into_iter().collect::<Vec<_>>();',
   'return self.construct_constructor_internal( realm, &constructor, &constructor, &arguments, '
   ');')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array.rs',
  'call_array_of',
  ('let constructor = match self.constructor_from_value(realm, this_value)?',
   'match self.construct_constructor_internal( realm, &constructor, &constructor, '
   '&[Self::array_length_value(length)], )? {')),
 ('stage3b-species-constructor',
  'src/engine/builtins/array.rs',
  'array_species_create',
  ('let constructor = match self.constructor_from_value(realm, constructor)?',
   'self.construct_constructor_internal( realm, &constructor, &constructor, &[Value::number(length '
   'as f64)], )')))

NATIVE_OWNED_PROTOTYPE_CONSUMERS = (('src/engine/heap/runtime/mod.rs', 'call_function_constructor'),
 ('src/engine/heap/runtime/mod.rs', 'call_primitive_constructor'),
 ('src/engine/builtins/array_buffer.rs', 'array_buffer_prototype_from_new_target'),
 ('src/engine/builtins/error/mod.rs', 'call_error_constructor'),
 ('src/engine/builtins/iterator/mod.rs', 'iterator_prototype_from_new_target'),
 ('src/engine/builtins/map.rs', 'map_prototype_from_new_target'),
 ('src/engine/builtins/promise.rs', 'promise_prototype_from_new_target'),
 ('src/engine/builtins/set.rs', 'set_prototype_from_new_target'),
 ('src/engine/builtins/shared_array_buffer.rs', 'shared_array_buffer_prototype_from_new_target'),
 ('src/engine/builtins/weak_collection.rs', 'weak_collection_prototype_from_new_target'),
 ('src/engine/builtins/weak_ref.rs', 'weak_intrinsic_prototype_from_new_target'),
 ('src/engine/builtins/array_buffer/data_view.rs', 'data_view_prototype_from_new_target'),
 ('src/engine/builtins/array_buffer/typed_array.rs', 'typed_array_prototype_from_new_target'),
 ('src/engine/builtins/date/constructor.rs', 'date_prototype_from_new_target'),
 ('src/engine/builtins/regexp/constructor.rs', 'allocate_regexp_from_new_target'))

CONSTRUCTOR_ONLY_ITEMS = (('stage3b-proxy-construct-order', 'src/engine/object/internal_methods.rs', 'construct_proxy'),
 ('stage3b-species-constructor',
  'src/engine/builtins/array_buffer/typed_array/species.rs',
  'typed_array_create_from_constructor_arguments'),
 ('stage3b-species-constructor', 'src/engine/builtins/array.rs', 'array_from_result'),
 ('stage3b-species-constructor', 'src/engine/builtins/array.rs', 'call_array_of'),
 ('stage3b-species-constructor', 'src/engine/builtins/array.rs', 'array_species_create'))

SPECIES_FUNCTIONS = (('src/engine/builtins/array_buffer.rs', 'array_buffer_species_constructor', True),
 ('src/engine/builtins/shared_array_buffer.rs', 'shared_array_buffer_species_constructor', True),
 ('src/engine/builtins/promise.rs', 'promise_species_constructor', True),
 ('src/engine/builtins/regexp/constructor.rs', 'regexp_species_constructor', False))

STAGE3B_RUNTIME_TEST_CONTRACTS = (('trusted_quickjs_ordinary_apply_admits_only_canonical_typed_kinds',
  ('for (magic, expected_kind) in [(0, ApplyKind::Call), (1, ApplyKind::Construct)] {',
   'for magic in [2_u16, u16::MAX] {',
   'assert_eq!(runtime.heap_counts(), baseline);')),
 ('trusted_quickjs_ordinary_apply_preserves_object_list_call_and_construct_semantics',
  ('&[target, receiver, list]',
   '&[constructor, new_target.clone(), list]',
   'context.get_property(&instance, &sum).unwrap()')),
 ('trusted_quickjs_ordinary_apply_nullish_lists_use_raw_receiver_for_both_kinds',
  ('assert!(!runtime.is_constructor(target_object).unwrap());',
   'for magic in [0_u8, 1] {',
   'for argument_array in [Value::Null, Value::Undefined] {')),
 ('trusted_quickjs_ordinary_apply_preserves_error_order_realm_and_pending_identity',
  ('native_error_prototypes[NativeErrorKind::Type.index()]',
   'caller.take_exception().unwrap().unwrap()',
   '&[target, receiver.clone(), Value::Null]')),
 ('trusted_quickjs_ordinary_apply_raw_prototype_get_preserves_order_and_receiver',
  ('Value::Int(17), empty.clone()',
   'context.take_exception().unwrap().unwrap()',
   'Some(context.object_prototype().unwrap())')),
 ('trusted_quickjs_ordinary_apply_construct_preserves_raw_new_target_across_dispatch',
  ('NativeFunctionId::ConstructorProbe',
   'set_constructor_bit(native.as_object(), true)',
   'Value::Int(17), empty.clone()')),
 ('construct_only_proxy_and_new_target_do_not_require_call_capability',
  ('runtime.as_callable(&proxy).unwrap().is_none()',
   'VmHost::construct(',
   'runtime.set_constructor_bit(&new_target, true)')),
 ('trusted_quickjs_ordinary_apply_raw_calling_realm_functions_fall_back_to_the_caller',
  ('execute_pending_job()',
   'Some(caller.realm)',
   'runtime.set_constructor_bit(&revoke_object, false)')),
 ('trusted_quickjs_ordinary_apply_raw_native_constructors_use_class_fallbacks',
  ('NativeFunctionId::ArrayConstructor',
   'for (label, constructor_source, arguments_source) in cases {',
   'Some(expected_prototype)')),
 ('trusted_quickjs_ordinary_apply_verifies_stack_and_reindexed_branch_targets',
  ('const UNDERFLOW: &str',
   'for (label, code, max_stack, expected) in [',
   'Instruction::Goto(9)',
   'Instruction::Apply(ApplyKind::Call)')))

STAGE3C_TEST_MODULE_CONTRACTS = (('src/engine/heap/runtime/mod.rs', ';'),
 ('src/engine/vm/mod.rs', '{'),
 ('src/engine/code/bytecode.rs', '{'),
 ('src/engine/code/binary_object/function_translate/mod.rs', '{'),
 ('src/engine/code/binary_object/ordinary_leaf.rs', '{'),
 ('src/engine/code/binary_object_publish.rs', '{'),
 ('src/engine/code/binary_object/function_translate/capability.rs', '{'))

STAGE3C_REQUIRED_TEST_SOURCES = {'src/engine/code/bytecode.rs',
 'src/engine/code/binary_object/function_translate/capability.rs',
 'src/engine/code/binary_object/function_translate/mod.rs',
 'src/engine/code/binary_object/ordinary_leaf.rs',
 'src/engine/code/binary_object_publish.rs',
 'src/engine/heap/runtime/tests.rs',
 'src/engine/vm/mod.rs'}

STAGE3C_TEST_CONTRACTS = (('src/engine/code/binary_object/function_translate/capability.rs',
  'registry_locks_the_current_physical_cohorts',
  ('(110, 1, 104, 29)',
   'assert_eq!(ordinary_only + shared, 133);',
   'assert_eq!(scalar_only + ordinary_only + shared, 134);')),
 ('src/engine/code/binary_object/function_translate/capability.rs',
  'ordinary_invocation_addition_is_the_exact_reviewed_six_row_set',
  ('(35, OpcodeFormat::NPop, Recipe::TailCall)',
   '(37, OpcodeFormat::NPop, Recipe::TailCallMethod)',
   'CapabilityPolicy::OrdinaryOnly(expected_recipe)')),
 ('src/engine/code/binary_object/function_translate/capability.rs',
  'blocked_frontier_has_stable_typed_category_counts',
  ('let mut counts = [0_usize; 15];',
   'assert!(counts.into_iter().all(|count| count != 0));',
   'assert_eq!(counts.into_iter().sum::<usize>(), 110);')),
 ('src/engine/code/binary_object/function_translate/mod.rs',
  'tail_invocation_lowering_preserves_the_npop_operand_and_kind',
  ('NativeOperands::NPop(u16::MAX)',
   '(false, FunctionOp::TailCall(u16::MAX))',
   '(true, FunctionOp::TailCallMethod(u16::MAX))')),
 ('src/engine/code/binary_object/ordinary_leaf.rs',
  'tail_invocation_operands_reach_the_ordinary_dto_unchanged',
  ('FunctionOp::TailCall(u16::MAX)',
   'OrdinaryLeafOp::TailCall(u16::MAX)',
   'OrdinaryLeafOp::TailCallMethod(u16::MAX)')),
 ('src/engine/code/binary_object_publish.rs',
  'ordinary_tail_invocation_publishes_one_for_one_with_the_unchanged_operand',
  ('OrdinaryLeafOp::TailCall(u16::MAX)',
   'Instruction::TailCall(u16::MAX)',
   'Instruction::TailCallMethod(u16::MAX)',
   'assert_eq!(next_synthetic_index, 0);')),
 ('src/engine/code/bytecode.rs',
  'verifier_models_tail_invocations_as_terminal_zero_result_operations',
  ('Instruction::TailCall(2)',
   'Instruction::TailCallMethod(2)',
   'for instruction in [Instruction::TailCall(0), Instruction::TailCallMethod(0)]',
   'Instruction::TailCall(u16::MAX)',
   'Instruction::TailCallMethod(u16::MAX)')),
 ('src/engine/vm/mod.rs',
  'tail_invocations_complete_the_frame_with_exact_call_operands',
  ('Completion::Return(Value::Int(42))',
   'Value::Undefined, vec![Value::Int(11), Value::Int(12)]',
   'Value::Int(21), Value::Int(20), vec![Value::Int(22), Value::Int(23)]')),
 ('src/engine/vm/mod.rs',
  'tail_invocation_throws_use_the_activation_backtrace_and_catch_path',
  ('Completion::Throw(Value::Int(77))',
   'assert_eq!(host.backtrace_values, [Value::Int(77)]);',
   'assert_eq!(host.captured_local_reuse_preparations, 1);',
   'Completion::Throw(Value::Int(88))')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_invocations_use_exact_bc5_wires_and_semantics',
  ('assert_eq!(QUICKJS_ORDINARY_TAIL_CALL_BC5.len(), 57);',
   '0x8ff9_d2c1_0c7e_2228',
   'assert_eq!(QUICKJS_ORDINARY_TAIL_CALL_METHOD_BC5.len(), 62);',
   '0xe87d_54c0_a2a1_40ca',
   'Instruction::TailCall(2)',
   'Instruction::TailCallMethod(2)')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_invocation_failures_are_recoverable',
  ('vec![Value::Int(0), Value::Int(1), Value::Int(2)]',
   'vec![Value::Null, Value::Int(0), Value::Int(1), Value::Int(2)]',
   'Err(RuntimeError::Exception)',
   'Value::Int(42)')),
 ('src/engine/heap/runtime/tests.rs',
  'trusted_quickjs_ordinary_tail_verification_rolls_back_heap_and_atoms',
  ('quickjs_ordinary_three_argument_with_code(&[0x23, 0xff, 0xff], 0)',
   'quickjs_ordinary_four_argument_with_code(&[0x25, 0xff, 0xff], 0)',
   'assert_eq!(runtime.heap_counts(), baseline',
   'assert_eq!(runtime.test_atom_count(), baseline_atoms')),
 ('src/engine/heap/runtime/tests.rs',
  'published_tail_call_uses_backtrace_and_current_activation_catch_semantics',
  ('Instruction::TailCall(0)',
   'let stack = own_stack_string(&runtime, &error).to_utf8_lossy();',
   'Instruction::Catch(4)',
   'Value::Int(17)')))

STAGE3C_TEST_BODY_HASHES = {('src/engine/code/binary_object/function_translate/capability.rs', 'registry_locks_the_current_physical_cohorts'): '1c74d3733c3b55d08359e7c3b9a9f76babb0f59f841c4306311a054dba0f1b00',
 ('src/engine/code/binary_object/function_translate/capability.rs', 'ordinary_invocation_addition_is_the_exact_reviewed_six_row_set'): '0bd25bc945bde404ea911c720491e06a0d58c7257683347372b6c74843d3afc2',
 ('src/engine/code/binary_object/function_translate/capability.rs', 'blocked_frontier_has_stable_typed_category_counts'): 'f2d596485d43e0c5ca2a0c77e5f332b893c54dfa6cfdbfc2367a476bd2071ec2',
 ('src/engine/code/binary_object/function_translate/mod.rs', 'tail_invocation_lowering_preserves_the_npop_operand_and_kind'): 'f9a36b2d07545f80276edce3e1e7f3e1baaa56fcdfd82996a857be1958acccd2',
 ('src/engine/code/binary_object/ordinary_leaf.rs', 'tail_invocation_operands_reach_the_ordinary_dto_unchanged'): 'fd78ceeb26a50bc988ebb4fdece4f4417b89abd31bbfe0edae6480899e8c1ecc',
 ('src/engine/code/binary_object_publish.rs', 'ordinary_tail_invocation_publishes_one_for_one_with_the_unchanged_operand'): '7277c89d2d824c8bfe59cecc5ed5fdbf4e68f0368b719794d3072df7782bc94e',
 ('src/engine/code/bytecode.rs', 'verifier_models_tail_invocations_as_terminal_zero_result_operations'): '67b24ba74d50030e6dacc306fc68641ba838e33abad42388209c53a080d26915',
 ('src/engine/vm/mod.rs', 'tail_invocations_complete_the_frame_with_exact_call_operands'): '0745b22ec76c903693df4dcd2380646a1846204a005c5e595dfcb4054a4d4f53',
 ('src/engine/vm/mod.rs', 'tail_invocation_throws_use_the_activation_backtrace_and_catch_path'): '55580f9eaaced1ad6733f50126d885d34ac1944ca6e6d5f889a98e4699abd82c',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_invocations_use_exact_bc5_wires_and_semantics'): '4b972572d236f13acf54b98365cd4c8ad52bd86e5a9dc97cbb67b727a8540562',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_invocation_failures_are_recoverable'): '0640226781baa7b22b4a68b2c1d0929ee1c60e09c347c1ebd9f23ed21bfd6235',
 ('src/engine/heap/runtime/tests.rs', 'trusted_quickjs_ordinary_tail_verification_rolls_back_heap_and_atoms'): 'e089f00738beddf2de2926d27f59850eb34b4a806184177deb9922228a0cc767',
 ('src/engine/heap/runtime/tests.rs', 'published_tail_call_uses_backtrace_and_current_activation_catch_semantics'): '898b42586dcc7d3a094d4146650a6536614e400103d580a9ee2f652592ab7508'}
